module Stash (secretStash) where

secretStash :: [String]
secretStash =
  [ "Account",
    "Address",
    "Asset",
    "Block",
    "Blockchain",
    "Brain Wallet",
    "Cryptocurrency",
    "Decentralize",
    "Decentralization",
    "Encrypted vs Unencrypted Keys",
    "Encryption",
    "Entropy",
    "Ethereum vs. Ether",
    "Hardware Wallet",
    "Hashing",
    "Hexadecimal",
    "Key Derivation",
    "Cryptographic key derivation",
    "Keystore File",
    "Mining",
    "Multisignature Address",
    "Secret Recovery Phrase",
    "Non Fungible Token",
    "Password storage",
    "Private Key",
    "Proof of Stake",
    "Proof of Work",
    "Pseudonymous",
    "Public Key",
    "Security Token",
    "Seed",
    "Smart Contracts",
    "Stablecoin",
    "Token",
    "Trustless",
    "Unpermissioned",
    "Permissioned Ledger",
    "Utility Token",
    "Wallet"
  ]